name: Authenticated and Unauthenticated Test

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: ticket-booking-k8s.obsessionforlearning.com
  STATE_STORE: s3://ticket-booking-k8s
  NAMESPACE: default
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  SECRET_ID: ${{ secrets.SECRET_ID }}

jobs:
  auth-test:
    name: Authentication Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Kops
        run: |
          curl -LO https://github.com/kubernetes/kops/releases/latest/download/kops-linux-amd64
          chmod +x kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops

      - name: Export Kops Cluster Configuration
        run: |
          export KOPS_STATE_STORE=$STATE_STORE
          kops export kubecfg --name $CLUSTER_NAME --state=$STATE_STORE --admin

      - name: Show HPA Status Before Testing
        run: |
          echo "HPA status before testing:"
          kubectl get hpa

      - name: Simulate Unauthenticated Request (Expected 401)
        run: |
          echo "Sending unauthenticated request (should fail with 401)..."
          curl -X PUT \
            -H "Content-Type: application/json" \
            -d '{"ticket_id": "dummy123", "user": "test_user", "status": "pending"}' \
            -w "\nHTTP Status: %{http_code}\n" \
            "http://ticket-booking.obsessionforlearning.com/ticket" || echo "Call failed"
          echo "----------------------------------------"

      - name: Generate Authentication Token
        run: |
          TOKEN=$(curl -X POST "https://eu-central-1qyxweokre.auth.eu-central-1.amazoncognito.com/oauth2/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$SECRET_ID&scope=default-m2m-resource-server-o3yhkn/read" \
            | jq -r '.access_token')
          if [ -z "$TOKEN" ]; then
            echo "Failed to generate token"
            exit 1
          fi
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "Successfully generated authentication token."

      - name: Simulate Authenticated Request (Expected 200)
        run: |
          echo "Sending authenticated request..."
          curl -X PUT -H "Authorization: Bearer $TOKEN" \
            -w "\nHTTP Status: %{http_code}\n" \
            "http://ticket-booking.obsessionforlearning.com/ticket" || echo "Call failed"
          echo "----------------------------------------"

      - name: Simulate Failure Scenario - Seats Booking Issue
        run: |
          echo "Sending authenticated request (simulateBookingFailure=seats)..."
          curl -X PUT -H "Authorization: Bearer $TOKEN" \
            -w "\nHTTP Status: %{http_code}\n" \
            "http://ticket-booking.obsessionforlearning.com/ticket?simulateBookingFailure=seats" || echo "Call failed"
          echo "----------------------------------------"

      - name: Simulate Failure Scenario - Ticket Booking Issue
        run: |
          echo "Sending authenticated request (simulateBookingFailure=ticket)..."
          curl -X PUT -H "Authorization: Bearer $TOKEN" \
            -w "\nHTTP Status: %{http_code}\n" \
            "http://ticket-booking.obsessionforlearning.com/ticket?simulateBookingFailure=ticket" || echo "Call failed"
          echo "----------------------------------------"

      - name: Show HPA Status After Testing
        run: |
          echo "HPA status after test:"
          kubectl get hpa
